#!/bin/bash

sudo apt update && sudo apt upgrade -y

wifi_name=$(zenity --entry --title="WiFi Name" --text="Enter the WiFi Name, make sure the computer is connected to that WiFi in the settings" 2> "/dev/null")
wifi_key=$(zenity --entry --title="Enter WiFi Password" --text="Enter WiFi Password" 2> "/dev/null")
zenity --info --title="WiFi name" --text="WiFi name in use.\n\n $wifi_name" 2> "/dev/null"

ip_address=$(zenity  --list  --text "Choose your IP address" --radiolist  --column "Pick" --column "IP address" TRUE $(hostname -I | cut -f1 -d' ') FALSE $(hostname -I | cut -f2 -d' ') FALSE $(hostname -I | cut -f3 -d' ') 2> "/dev/null")
zenity --info --title="IP address" --text="Server IP address in use.\n\n "$ip_address"" 2> "/dev/null"

project_id=$(zenity --entry --title="DialogFLow Project ID" --text="Enter the DialogFlow Project ID.\n\n Find it in Project settings of the associated project in the Actions console or in DialogFlow." 2> "/dev/null")
device_id=$(zenity --entry --title="Device model" --text="Enter the Device Model ID.\n\n Find it in Project settings of the associated project in the Actions console." 2> "/dev/null")
model_id=$(zenity --entry --title="Device model" --text="Enter the Device Model ID.\n\n Find it in Develop tab, Device registration on the left menu of the associated project in the Actions console." 2> "/dev/null")

wget http://downloads.libelium.com/waspmote-pro-ide-v06.19-linux64.zip
unzip waspmote-pro-ide-v06.19-linux64.zip -d wasp1
sudo ./wasp1/install.sh

update-alternatives --remove python /usr/bin/python2
sudo update-alternatives --remove python /usr/bin/python2
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

sudo apt install mysql-server

mysql -uroot -p1212 -e "CREATE DATABASE calm_computing3;"

mysql -uroot -p1212 -e "USE calm_computing3;"

mysql -uroot -p1212 -e "CREATE TABLE calm_computing3.mlibelium_1(id int AUTO_INCREMENT, date varchar(30), time varchar(30), temperature varchar(30), pressure varchar(30), humidity varchar(30), lux varchar(30), lumen varchar(30), primary key(id));"

mysql -uroot -p1212 -e "CREATE TABLE calm_computing3.mlibelium_2(id int AUTO_INCREMENT, date varchar(30), time varchar(30), CO varchar(30), temperature varchar(30), pressure varchar(30), humidity varchar(30), primary key(id));"

mysql -uroot -p1212 -e "CREATE TABLE calm_computing3.mwatch_1(id int AUTO_INCREMENT, date varchar(30), time varchar(30), heart_rate varchar(30), primary key(id));"

mysql -uroot -p1212 -e "CREATE TABLE calm_computing3.mphone_1(id int AUTO_INCREMENT, date varchar(30), time varchar(30), device_state varchar(30), call_state varchar(30), primary key(id));"

# mysql -uroot -proot -e "CREATE DATABASE calm_computing1;"

# mysql -uroot -proot -e "USE DATABASE calm_computing1;"

# mysql -uroot -proot -e "CREATE TABLE calm_computing.mlibelium_1(id int AUTO_INCREMENT, date varchar(30), time varchar(30), temperature varchar(30), pressure varchar(30), humidity varchar(30), lux varchar(30), lumen varchar(30), primary key(id));"

# mysql -uroot -proot -e "CREATE TABLE calm_computing.mlibelium_2(id int AUTO_INCREMENT, date varchar(30), time varchar(30), CO varchar(30), temperature varchar(30), pressure varchar(30), humidity varchar(30), primary key(id));"

# mysql -uroot -proot -e "CREATE TABLE calm_computing.mwatch_1(id int AUTO_INCREMENT, date varchar(30), time varchar(30), heart_rate varchar(30), primary key(id));"

# mysql -uroot -proot -e "CREATE TABLE calm_computing.mphone_1(id int AUTO_INCREMENT, date varchar(30), time varchar(30), device_state varchar(30), call_state varchar(30), primary key(id));"

sudo apt-get install python3-dev python3-venv -y
python3 -m venv ~/env

source ~/env/bin/activate

pip3 install --upgrade pip setuptools wheel
pip3 install wheel
sudo apt install authbind -y
sudo apt-get install build-essential libssl-dev libffi-dev python3-dev -y
sudo apt-get install libmysqlclient-dev -y
sudo apt-get install portaudio19-dev libffi-dev libssl-dev -y
pip install pyyaml

python -m pip install --upgrade google-assistant-sdk[samples]
python -m pip install --upgrade google-auth-oauthlib[tool]

pip3 install flask-mysqldb
pip3 install mysql-connector-python-rf
sudo apt-get install python-mysqldb -y
pip install flask-assistant
pip3 install pygal 
cd mysql-connector-python-2.1.6/
sudo python3 setup.py install
cd ..

sudo touch /etc/authbind/byport/80
sudo chmod 777 /etc/authbind/byport/80

file_name=$(zenity --file-selection --title="Select the client secrets JSON file downloaded in Step 14 of the Installation manual" 2> "/dev/null")

case $? in
         0)
                zenity --info --title="File name" --text="File name in use.\n\n $file_name" 2> "/dev/null";;
         1)
                zenity --info --title="No file selected" --text="No file selected.\n" 2> "/dev/null";;
        -1)
                zenity --info --title="Unexpected error occured" --text="Unexpected error occured.\n" 2> "/dev/null";;
esac

google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype --save --headless --client-secrets "$file_name"

sed -e "s/replace_the_model_id/$model_id/g" -e "s/replace_the_device_id/$device_id/g" ./calm_com/bak_textinput.py > ./calm_com/textinput.py 2> "/dev/null"

sed -e "s/replace_the_ip_address/$ip_address/g" -e "s/replace_the_project_id/$project_id/g" ./calm_com/bak_app.py > ./calm_com/app.py 2> "/dev/null"

sed "s/replace_the_ip_address/$ip_address/g" ./calm_com/templates/bak_libelium_1_rt.html > ./calm_com/templates/libelium_1_rt.html 2> "/dev/null"
sed "s/replace_the_ip_address/$ip_address/g" ./calm_com/templates/bak_libelium_2_rt.html > ./calm_com/templates/libelium_2_rt.html 2> "/dev/null"
sed "s/replace_the_ip_address/$ip_address/g" ./calm_com/templates/bak_phone_1.html > ./calm_com/templates/phone_1.html 2> "/dev/null"
sed "s/replace_the_ip_address/$ip_address/g" ./calm_com/templates/bak_watch_1_rt.html > ./calm_com/templates/watch_1_rt.html 2> "/dev/null"

sed "s/replace_the_ip_address/$ip_address/g" ./1/main_http/bak_main_http.pde > ./1/main_http/main_http.pde 2> "/dev/null"
sed "s/replace_the_ip_address/$ip_address/g" ./2/main_http/bak_main_http.pde > ./2/main_http/main_http.pde 2> "/dev/null"

sed -e "s/replace_the_ssid_name/$wifi_name/g" -e "s/replace_the_key_name/$wifi_key/g" ./1/WIFI_PRO_01_configure_essid/bak_WIFI_PRO_01_configure_essid.pde > ./1/WIFI_PRO_01_configure_essid/WIFI_PRO_01_configure_essid.pde 2> "/dev/null"
sed -e "s/replace_the_ssid_name/$wifi_name/g" -e "s/replace_the_key_name/$wifi_key/g" ./2/WIFI_PRO_01_configure_essid/bak_WIFI_PRO_01_configure_essid.pde > ./2/WIFI_PRO_01_configure_essid/WIFI_PRO_01_configure_essid.pde 2> "/dev/null"

sed "s/replace_the_ip_address/$ip_address/g" ./1/WIFI_PRO_02_join/bak_WIFI_PRO_02_join.pde > ./1/WIFI_PRO_02_join/WIFI_PRO_02_join.pde 2> "/dev/null"
sed "s/replace_the_ip_address/$ip_address/g" ./2/WIFI_PRO_02_join/bak_WIFI_PRO_02_join.pde > ./2/WIFI_PRO_02_join/WIFI_PRO_02_join.pde 2> "/dev/null"

sed "s/replace_the_ip_address/$ip_address/g" ./1/WIFI_PRO_05_ping/bak_WIFI_PRO_05_ping.pde > ./1/WIFI_PRO_05_ping/WIFI_PRO_05_ping.pde 2> "/dev/null"
sed "s/replace_the_ip_address/$ip_address/g" ./2/WIFI_PRO_05_ping/bak_WIFI_PRO_05_ping.pde > ./2/WIFI_PRO_05_ping/WIFI_PRO_05_ping.pde 2> "/dev/null"
